[package]
name = "test_implementation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdxsort = "0.3.0"
criterion = "0.5.1"

[[bench]]
name = "bench_init"
harness = false